# -*- coding: utf-8 -*-
"""
/***************************************************************************
 NgToolbox
                                 A QGIS plugin
 NextGIS Toolbox provider for QGIS
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2023-02-13
        git sha              : $Format:%H$
        copyright            : (C) 2023 by NextGIS
        email                : info@nextgis.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os.path

from qgis.PyQt.QtCore import QCoreApplication, Qt, QTranslator
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QDockWidget, QMessageBox

from nextgis_toolbox.about_dialog import AboutDialog
from nextgis_toolbox.core import utils
from nextgis_toolbox.core.constants import PACKAGE_NAME, PLUGIN_NAME
from nextgis_toolbox.nextgis_toolbox_window import ToolboxDockWidget


class NgToolboxPlugin:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        self.dockWidget = None
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale_path = os.path.join(
            self.plugin_dir, "i18n", f"{PACKAGE_NAME}_{utils.locale()}.qm"
        )

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate("NgToolbox", message)

    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        checkable=False,
        is_checked=False,
        status_tip=None,
        whats_this=None,
        parent=None,
    ):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """
        if icon_path:
            icon = QIcon(icon_path)
            action = QAction(icon, text, parent)
        else:
            action = QAction(text, parent)
        action.setEnabled(enabled_flag)
        action.setCheckable(checkable)
        if checkable:
            action.setChecked(is_checked)
        if not checkable:
            action.triggered.connect(callback)
        else:
            action.toggled.connect(callback)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(PLUGIN_NAME, action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = os.path.join(self.plugin_dir, "icons", "icon.png")
        self.showAction = self.add_action(
            icon_path,
            text=self.tr("NextGIS Toolbox"),
            checkable=True,
            is_checked=False,
            callback=self.run,
            parent=self.iface.mainWindow(),
        )
        self.actionAbout = self.add_action(
            icon_path=None,
            text=self.tr("About"),
            add_to_toolbar=False,
            checkable=False,
            is_checked=False,
            callback=self.about,
            parent=self.iface.mainWindow(),
        )

        self.first_start = True

    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(PLUGIN_NAME, action)
            self.iface.removeToolBarIcon(action)
            action.deleteLater()
        if self.dockWidget:
            self.dockWidget.unload_proc()
            self.dockWidget.close()

    def set_unchecked(self):
        self.showAction.setChecked(False)

    def about(self):
        dialog = AboutDialog(os.path.basename(self.plugin_dir))
        dialog.exec()

    def run(self):
        """Run method that performs all the real work"""

        if self.first_start and self.showAction.isChecked():
            self.first_start = False
            try:
                self.dockWidget = ToolboxDockWidget(
                    self.iface, self.iface.mainWindow()
                )
                self.dockWidget.window_closed.connect(self.set_unchecked)
            except Exception:
                QMessageBox.about(
                    None,
                    None,
                    self.tr("Error loading NextGIS Toolbox plugin!"),
                )
                self.showAction.setChecked(False)
                self.first_start = True
                return
            self.iface.addDockWidget(Qt.LeftDockWidgetArea, self.dockWidget)
            self.iface.mainWindow().tabifyDockWidget(
                [
                    dock
                    for dock in self.iface.mainWindow().findChildren(
                        QDockWidget
                    )
                    if self.iface.mainWindow().dockWidgetArea(dock)
                    == Qt.LeftDockWidgetArea
                ][0],
                self.dockWidget,
            )
        elif not self.dockWidget:
            return
        if self.showAction.isChecked():
            self.dockWidget.setVisible(True)
        else:
            self.dockWidget.setVisible(False)
